### ISSUE TITLE
Domain is no longer available

### ISSUE THREAD

**Issue by FlorianBoe** [marcus-herrmann/a11y-act.eu#18]
I just went over the site and saw that you link to https://directive2102.eu/ at the bottom of the site. The domain is no longer available, a useful alternative might be https://digital-strategy.ec.europa.eu/en/policies/web-accessibility-directive-standards-and-harmonisation

PS: We saw each other a few times last year at the Accessibility Club IAAP learning group.

**Comment by FlorianBoe** [comment]
I just realized that you once owned this domain yourself. The solution may therefore be different, the link still leads to nowhere. 😀

**Comment by marcus-herrmann** [comment]
Thanks for the hint! I let that other domain slip, but fixed a11y-act.eu according to your idea.
